# Site settings
title: Amy C. Rager, Ph.D. # Your name
logo: /assets/img/logo.png
# logo: /assets/img/IMG_1547.jpeg
email: amy.c.rager@nasa.gov
description: >-
  Physicist, systems engineer, and science operations manager with expertise in Python, data analysis, and ground system engineering. Passionate about driving mission success through innovative solutions, interdisciplinary collaboration, and scalable system design.
baseurl: "" # Leave this blank for GitHub Pages root
url: "https://acrager.github.io" # The base URL of your site
github_username: acrager
repository: acrager/acrager.github.io
# Layout and customization
# theme: minima # Current theme; switch to your preferred theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed

# Build settings
markdown: kramdown # Use the default markdown processor
highlighter: rouge  # Syntax highlighting for code blocks

# Exclude unnecessary directories/files
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock